# Copyright 2024 Khalil Estell
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 📚 Deploy APIs

on:
  workflow_call:
    inputs:
      version:
        type: string
        default: ""
  workflow_dispatch:

permissions:
  contents: write

jobs:
  api_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: sudo apt install doxygen
      - run: pip install -r sphinx/requirements.txt
      - run: git config user.name ci-bot
      - run: git config user.email ci-bot@example.com

      - run: rm -rf sphinx/doxygen
      - run: mkdir sphinx/doxygen
      - run: doxygen Doxyfile
      - run: sphinx-build -b html sphinx docs/api/latest
